# Generated by Django 2.0.5 on 2018-08-14 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diposit',
            name='user',
            field=models.ForeignKey(on_delete='Cascade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(on_delete='Cascade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(on_delete='Cascade', to=settings.AUTH_USER_MODEL),
        ),
    ]
